name: CMake
on: [push]

env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        include:
          - os: ubuntu-latest
          - os: windows-latest
    steps:
      - name: Install prerequisites
        if: runner.os == 'Linux'
        run: sudo apt install -y libsdl2-dev uuid-dev
      - uses: actions/checkout@v2
      - name: Create Build environment
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
